package myus.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing a course recommendation generated by the AI Chatbot.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CourseSuggestionDTO {

    private Long courseOfferingId;
    private String courseCode;
    private String courseName;
    private int credits;
    private boolean prerequisiteCleared;
    private String reasonForRecommendation;
    private String schedule;
    private String instructor;
}
