package com.myus.dto.ai;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO representing a single course recommendation generated by the AI engine.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CourseSuggestionDTO {

    private Long courseOfferingId;
    private String courseCode;
    private String courseName;
    private Integer credits;
    private boolean prerequisiteCleared;
    private String reasonForRecommendation;
    private String prerequisiteStatus; // "CLEARED", "MISSING", "WAIVED"
}
