/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: ['class', '[data-theme="night"]'],
  theme: {
    extend: {
      colors: {
        // ── Brand (from dashboard.html + skylearn) ──
        primary: {
          DEFAULT: '#0061a4',
          container: '#2196f3',
          fixed: '#d1e4ff',
          'fixed-dim': '#9ecaff',
          hover: '#00497d',
          pressed: '#003c66',
          soft: 'rgba(0, 97, 164, 0.10)',
          ring: 'rgba(0, 97, 164, 0.22)',
        },
        secondary: {
          DEFAULT: '#21638d',
          container: '#95cfff',
          fixed: '#cbe6ff',
          'fixed-dim': '#93cdfc',
        },
        tertiary: {
          DEFAULT: '#2b5bb5',
          container: '#658fed',
          fixed: '#d9e2ff',
          'fixed-dim': '#b0c6ff',
        },
        accent: '#8b5cf6',
        // ── Semantic colors ──
        sun: { DEFAULT: '#fbbf24', bright: '#fcd34d', deep: '#d97706' },
        success: { DEFAULT: '#4CAF50', soft: '#E8F5E9', deep: '#2E7D32' },
        error: { DEFAULT: '#F44336', soft: '#ffdad6', deep: '#ba1a1a' },
        warning: { DEFAULT: '#FF9800', soft: '#FFF8E1' },
        pending: '#607D8B',
        // ── Surfaces (light blue theme) ──
        surface: {
          DEFAULT: 'var(--color-bg)',
          bright: 'var(--color-bg)',
          white: 'var(--color-surface-elevated)',
          dim: 'var(--color-surface)',
          container: {
            lowest: 'var(--color-surface-elevated)',
            low: 'var(--color-surface)',
            DEFAULT: 'var(--color-surface)',
            high: 'var(--color-header)',
            highest: 'var(--color-header)',
          },
          variant: 'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
        },
        // ── Borders ──
        border: {
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
          variant: '#bfc7d4',
          card: '#E3F2FD',
        },
        outline: { DEFAULT: '#707883', variant: '#bfc7d4' },
        // ── Text / Ink ──
        text: {
          primary: 'var(--color-text-primary)',
          DEFAULT: 'var(--color-text)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          faint: 'var(--color-text-faint)',
        },
        // ── Background ──
        background: '#f5faff',
        bg: 'var(--color-bg)',
        // ── Inverse ──
        'inverse-surface': '#24323a',
        'inverse-primary': '#9ecaff',
        'inverse-on-surface': '#e4f3fe',
        // ── Night mode surfaces (CSS var linked) ──
        dark: {
          surface: 'var(--color-surface)',
          header: 'var(--color-header)',
          sidebar: 'var(--color-sidebar)',
          'input-bg': 'var(--color-input-bg)',
        },
      },
      fontFamily: {
        display: ["'Inter'", "'Hubot Sans'", "'Nunito'", 'system-ui', 'sans-serif'],
        body: ["'Inter'", "'Atkinson Hyperlegible'", 'system-ui', '-apple-system', 'sans-serif'],
        mono: ["'JetBrains Mono'", "'Courier New'", 'monospace'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        hero: ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        caption: ['0.875rem', { lineHeight: '1.4' }],
        small: ['1rem', { lineHeight: '1.5' }],
        body: ['1.125rem', { lineHeight: '1.6' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.5rem',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '28px',
        full: '9999px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        card: '0px 2px 8px rgba(0,0,0,0.12)',
        'card-hover': '0px 4px 16px rgba(0,0,0,0.10)',
        'focus-ring': 'var(--focus-ring)',
        'primary-glow': '0 2px 12px rgba(0,97,164,0.20)',
        'primary-glow-lg': '0 4px 20px rgba(0,97,164,0.30)',
      },
      backdropBlur: { glass: '16px', 'glass-heavy': '20px', 'glass-light': '12px' },
      transitionDuration: { fast: '160ms', base: '240ms', slow: '400ms' },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '24px',
        'margin-mobile': '16px',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        8: '2rem',
        12: '3rem',
        16: '4rem',
      },
      keyframes: {
        sunPulse: { '0%,100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.06)' } },
        sunRayRotate: { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        sparkleFloat: {
          '0%': { transform: 'translateY(0) translateX(0) scale(0.4)', opacity: '0' },
          '15%': { opacity: '1', transform: 'scale(1.1)' },
          '70%': { opacity: '0.3', transform: 'translateY(-35vh) translateX(4px) scale(0.7)' },
          '100%': { transform: 'translateY(-60vh) translateX(-3px) scale(0.2)', opacity: '0' },
        },
        rippleExpand: {
          '0%': { width: '0', height: '0', opacity: '0.7' },
          '100%': { width: '100px', height: '100px', opacity: '0' },
        },
        sparkleBurst: {
          '0%': { transform: 'rotate(var(--a)) translateX(0) scale(1)', opacity: '1' },
          '100%': { transform: 'rotate(var(--a)) translateX(var(--d)) scale(0.1)', opacity: '0' },
        },
        twinkleA: {
          '0%,100%': { opacity: '0.15' },
          '12%': { opacity: '0.95' },
          '25%': { opacity: '0.10' },
          '38%': { opacity: '0.80' },
          '50%': { opacity: '0.20' },
          '62%': { opacity: '0.92' },
          '75%': { opacity: '0.08' },
          '88%': { opacity: '0.70' },
        },
        twinkleB: {
          '0%,100%': { opacity: '0.35' },
          '10%': { opacity: '0.98' },
          '22%': { opacity: '0.12' },
          '35%': { opacity: '0.90' },
          '48%': { opacity: '0.22' },
          '60%': { opacity: '0.95' },
          '72%': { opacity: '0.18' },
          '85%': { opacity: '0.78' },
        },
        twinkleC: {
          '0%,100%': { opacity: '0.25' },
          '18%': { opacity: '0.95' },
          '36%': { opacity: '0.15' },
          '54%': { opacity: '0.88' },
          '72%': { opacity: '0.20' },
          '90%': { opacity: '0.92' },
        },
        twinkleD: {
          '0%,100%': { opacity: '0.40' },
          '15%': { opacity: '0.98' },
          '30%': { opacity: '0.15' },
          '50%': { opacity: '0.95' },
          '65%': { opacity: '0.18' },
          '80%': { opacity: '0.92' },
        },
        diamondPulse: {
          '0%,100%': { transform: 'scale(1) rotate(0deg)' },
          '25%': { transform: 'scale(1.35) rotate(0.5deg)' },
          '50%': { transform: 'scale(0.85) rotate(0deg)' },
          '75%': { transform: 'scale(1.25) rotate(-0.5deg)' },
        },
        driftSlow: {
          '0%': { transform: 'translate(0,0)' },
          '20%': { transform: 'translate(25px,-15px)' },
          '40%': { transform: 'translate(-18px,-28px)' },
          '55%': { transform: 'translate(-30px,8px)' },
          '70%': { transform: 'translate(15px,20px)' },
          '85%': { transform: 'translate(-10px,-5px)' },
          '100%': { transform: 'translate(0,0)' },
        },
        driftMedium: {
          '0%': { transform: 'translate(0,0) rotate(0deg)' },
          '22%': { transform: 'translate(35px,18px) rotate(0.5deg)' },
          '44%': { transform: 'translate(-22px,-28px) rotate(-0.4deg)' },
          '66%': { transform: 'translate(15px,-10px) rotate(0.3deg)' },
          '88%': { transform: 'translate(-30px,12px) rotate(-0.5deg)' },
          '100%': { transform: 'translate(0,0) rotate(0deg)' },
        },
        driftFast: {
          '0%': { transform: 'translate(0,0)' },
          '30%': { transform: 'translate(-40px,25px)' },
          '60%': { transform: 'translate(20px,-20px)' },
          '100%': { transform: 'translate(0,0)' },
        },
        nebulaDrift: {
          '0%': { backgroundPosition: '0% 50%, 100% 40%, 50% 60%' },
          '20%': { backgroundPosition: '25% 35%, 75% 60%, 40% 40%' },
          '40%': { backgroundPosition: '10% 65%, 95% 35%, 60% 55%' },
          '60%': { backgroundPosition: '30% 40%, 70% 65%, 45% 50%' },
          '80%': { backgroundPosition: '15% 55%, 85% 45%, 55% 35%' },
          '100%': { backgroundPosition: '0% 50%, 100% 40%, 50% 60%' },
        },
        nebulaPulse: {
          '0%,100%': { opacity: '0.42' },
          '20%': { opacity: '0.82' },
          '40%': { opacity: '0.48' },
          '60%': { opacity: '0.78' },
          '80%': { opacity: '0.55' },
        },
        meteorCycle: {
          '0%': { transform: 'translateY(0) translateX(0) rotate(25deg)', opacity: '0' },
          '2%': { opacity: '0' },
          '4%': { opacity: '1' },
          '8%': { opacity: '1' },
          '12%': { transform: 'translateY(70vh) translateX(-35vw) rotate(25deg)', opacity: '0.3' },
          '14%': { opacity: '0' },
          '100%': { transform: 'translateY(70vh) translateX(-35vw) rotate(25deg)', opacity: '0' },
        },
      },
      animation: {
        'sun-pulse': 'sunPulse 4s ease-in-out infinite',
        'sun-ray-rotate': 'sunRayRotate 60s linear infinite',
        'sparkle-float': 'sparkleFloat 6s ease-in infinite',
        'ripple-expand': 'rippleExpand 600ms ease-out forwards',
        'sparkle-burst': 'sparkleBurst 700ms ease-out forwards',
        'twinkle-a': 'twinkleA 3s ease-in-out infinite',
        'twinkle-b': 'twinkleB 2.6s ease-in-out infinite',
        'twinkle-c': 'twinkleC 3.2s ease-in-out infinite',
        'twinkle-d': 'twinkleD 3.8s ease-in-out infinite',
        'diamond-pulse': 'diamondPulse 16s ease-in-out infinite',
        'drift-slow': 'driftSlow 22s ease-in-out infinite',
        'drift-medium': 'driftMedium 28s ease-in-out infinite',
        'drift-fast': 'driftFast 18s ease-in-out infinite',
        'nebula-drift': 'nebulaDrift 20s ease-in-out infinite',
        'nebula-pulse': 'nebulaPulse 8s ease-in-out infinite',
        'meteor-cycle': 'meteorCycle 13s linear infinite',
      },
      maxWidth: { container: '1280px' },
    },
  },
  plugins: [],
};
